{"trial_id": "05", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "optimizer", "default": "sgd", "conditions": [], "values": ["sgd", "rmsprop", "adam", "adamw", "adadelta", "adagrad", "adamax", "adafactor", "nadam", "ftrl"], "ordered": false}}], "values": {"optimizer": "adafactor"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 266, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras_tuner\\engine\\base_tuner.py\", line 231, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 213, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 155, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras_tuner\\engine\\tuner.py\", line 146, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\CXR\\AppData\\Local\\Temp\\ipykernel_6116\\2466774364.py\", line 6, in build_model\n    model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"d:\\Python\\Deep-Learning\\openvino_env\\lib\\site-packages\\keras\\saving\\legacy\\serialization.py\", line 385, in class_and_config_for_serialized_keras_object\n    raise ValueError(\nValueError: Unknown optimizer: 'adafactor'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.\n"}